name: "Checkout"
description: "Clones a fresh or updates an existing repo"
inputs:
  token:
    required: true
    description: "The Personal Access Token for accessing the repository"
runs:
  using: "composite"
  steps:
    - name: Repo URL
      id: vars
      run: |
        REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git
        echo "Repo URL: $REPO_URL"
        echo "repo_url=$REPO_URL" >> $GITHUB_OUTPUT
      shell: bash

    - name: Configure GitHub credentials
      run: echo "https://x-access-token:${{ inputs.token }}@github.com" > ~/.git-credentials
      shell: bash

    - name: Fetch or clone
      run: |
        if [ -d .git ]
        then
          echo Resetting...
          git rm --cached -r . || true  # necessary but may fail when no files
          git reset --hard HEAD
          git clean -dfx
          git submodule foreach git reset --hard
          echo Fetching...
          git remote set-url origin ${{ steps.vars.outputs.repo_url }}  # get rid of wrong credentials
          git fetch
        else
          echo Cloning...
          git clone ${{ steps.vars.outputs.repo_url }} . \
            --no-checkout --depth 1
        fi
      shell: bash

    - name: Checkout
      run: |
        echo Checking out ${{ github.sha }}...
        git checkout ${{ github.sha }}
      shell: bash

    - name: Update submodules
      run: git submodule update --init --depth 1
      shell: bash

    - name: Show status
      run: git status
      shell: bash
